# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
# export LANG=en_US.UTF-8
target '{{cookiecutter.product_name}}' do
    # Comment the next line if you don't want to use dynamic frameworks
  source 'https://github.com/CocoaPods/Specs.git'
  
  use_frameworks!
  
  ## 第三方SDK
  # runScript => "${PODS_ROOT}/SwiftLint/swiftlint"
  pod 'SwiftFormat/CLI',                    "0.50.1"
  pod 'SwiftLint',                          '0.51.0'
  pod 'Schedule',                           "2.1.0"
  
#  # Pods-for-AppStore
#  pod 'UtilsKit',                        '1.0.5'

#
#  # Pods-for-Archive(Jenkins)
#  pod 'UtilsKit',                        :git => 'http://xxx/xxx/UtilsKit.git',                                                                               :tag => '1.0.5'
  
   # Pods-for-testing
#  pod 'UtilsKit',                        :path => '../../../../../Components/UtilsKit/Trunk'
   
end

## 检查是否安装插件
pre_install do |installer|
  # 插件路径
  sandbox_root = Pathname(installer.sandbox.root)
  ycroot = File.expand_path("../", sandbox_root)
  # lint-staged
  node_module_lint_stage = File.expand_path("node_modules/lint-staged/",ycroot)
  has_lint_stage = File.exist?(node_module_lint_stage)
  # husky
  node_module_husky = File.expand_path("node_modules/husky",ycroot)
  has_husky = File.exist?(node_module_husky)
  # commitizen
  node_module_commitizen = File.expand_path("node_modules/commitizen",ycroot)
  has_commitizen = File.exist?(node_module_commitizen)
  # cz-conventional-changelog
  node_module_changelog = File.expand_path("node_modules/cz-conventional-changelog",ycroot)
  has_changelog = File.exist?(node_module_changelog)
  # cz-customizable
  node_module_customizable = File.expand_path("node_modules/cz-customizable",ycroot)
  has_customizable = File.exist?(node_module_customizable)
  # commitlint
  node_module_commitlint = File.expand_path("node_modules/@commitlint",ycroot)
  has_commitlint = File.exist?(node_module_commitlint)
  
  if has_husky && has_lint_stage && has_commitizen && node_module_changelog && has_customizable && has_commitlint
    Pod::UI.puts "lint staged，husky，commitizen，cz-conventional-changelog，cz-customizable，commitlint 已安装"
  else
    raise "warning error： lint staged，husky，commitizen，cz-conventional-changelog，cz-customizable，commitlint不存在，请使用以下命令安装: npm install"
  end
end

# error: File not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a
post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
